// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  เปิด collection ที่ path — ขนาด guard → read → JSON → schema gate →
	 *  normalize → index → เก็บ recents (TC-CMD-001..015)
	 */
	openCollection: (path: string) => typedError<CollectionOverview, AppError>(__TAURI_INVOKE("open_collection", { path })),
	/**  re-read แหล่งที่เปิดอยู่จากดิสก์ แล้ว preserve `NodeId` เดิม (FR-045) */
	reloadCollection: () => typedError<CollectionOverview, AppError>(__TAURI_INVOKE("reload_collection")),
	/**  ปิด collection กลับสู่ shell — idempotent ไม่ error เมื่อเรียกซ้ำ (TC-CMD-030) */
	closeCollection: () => typedError<null, AppError>(__TAURI_INVOKE("close_collection")),
	/**
	 *  detail ของ node ตัวเดียว — O(1) arena lookup, ไม่ re-parse ไม่แตะไฟล์
	 *  (ADR-005 / TC-CMD-017..022); root (`""`) ให้ `UnknownNode` เพราะ detail ของ
	 *  collection อยู่ที่ overview อยู่แล้ว (TC-CMD-019/020)
	 */
	getNodeDetail: (nodeId: string) => typedError<NodeDetail, AppError>(__TAURI_INVOKE("get_node_detail", { nodeId })),
	/**  saved response ตัวเต็ม (S5) — body เป็น pieces แยกมาเฉพาะตัวที่ขอ (FR-037) */
	getExample: (nodeId: string, index: number) => typedError<ExampleDetail, AppError>(__TAURI_INVOKE("get_example", { nodeId, index })),
	/**
	 *  รายการ recents เรียง MRU (ใหม่สุดก่อน) ตั้งแต่ 10 ขึ้นไป (FR-041 / TC-CMD-031),
	 *  cap ที่ 20 (TC-U-044)
	 * 
	 *  store อ่านไม่ได้ → [`AppError::StoreUnavailable`] (ADR-013: ไม่ panic ไม่เงียบ)
	 *  — frontend ตัดสินใจเองว่าจะแสดง list ว่าง + คำเตือน (acceptance ของ T-010),
	 *  ส่วน open_collection เองต้องยังเปิดสำเร็จเสมอแม้ store เสีย (TC-CMD-034)
	 */
	listRecents: () => typedError<RecentEntry[], AppError>(__TAURI_INVOKE("list_recents")),
	/**
	 *  ลบ recent หนึ่งรายการตาม path — repair path เมื่อไฟล์หาย (FR-042); path ที่
	 *  ไม่อยู่ใน list เป็น no-op ไม่ error (TC-CMD-032)
	 */
	forgetRecent: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("forget_recent", { path })),
	/**  theme ปัจจุบัน — ยังไม่เคยตั้ง = `system` (FR-043, default ไม่ใช่ light) */
	getPreferences: () => typedError<Preferences, AppError>(__TAURI_INVOKE("get_preferences")),
	/**  ตั้ง theme — persist ข้าม restart (FR-043 / TC-U-046) */
	setPreferences: (prefs: Preferences) => typedError<null, AppError>(__TAURI_INVOKE("set_preferences", { prefs })),
};

/* Types */
/**
 *  Every distinct failure the UI must distinguish.
 * 
 *  Tagged `{ kind, detail }` on the wire (design.md §AppError wire shape). The `specta::Type`
 *  derive keeps `bindings.ts` in lockstep with this shape once T-008 wires `tauri-specta`.
 */
export type AppError = 
/**  The picked path does not exist. */
{ kind: "fileNotFound"; detail: {
	path: string,
} } | 
/**  The path exists but cannot be read (permission, a directory, invalid UTF-8, …). */
{ kind: "fileUnreadable"; detail: {
	path: string,
	reason: string,
} } | 
/**  Over the 64 MiB size guard of ADR-015, decided from metadata before any read. */
{ kind: "fileTooLarge"; detail: {
	sizeBytes: number,
	limitBytes: number,
} } | 
/**  Not valid JSON; `line`/`column` come straight from serde_json (FR-007). */
{ kind: "notJson"; detail: {
	line: number,
	column: number,
	message: string,
} } | 
/**  Valid JSON that is missing a field a collection requires (FR-006). */
{ kind: "notACollection"; detail: {
	missingField: string,
} } | 
/**  `info.schema` is not the v2.1 URL minim reads (FR-005). */
{ kind: "unsupportedSchema"; detail: {
	found: string,
	expected: string,
} } | 
/**  A command was invoked with no collection open. */
{ kind: "noCollectionOpen" } | 
/**  `get_node_detail` / `get_example` hit an unknown node id. */
{ kind: "unknownNode"; detail: {
	nodeId: string,
} } | 
/**  `get_example` hit an out-of-range example index. */
{ kind: "unknownExample"; detail: {
	nodeId: string,
	index: number,
} } | 
/**
 *  A store read/write failed. Non-fatal — the collection still opens, only persistence
 *  is degraded — but surfaced per ADR-013 (reported by T-010).
 */
{ kind: "storeUnavailable"; detail: {
	operation: StoreOperation,
	reason: string,
} } | 
/**
 *  A command whose signature is exported to `bindings.ts` but whose body a later task
 *  implements (T-009/T-010). Unreachable in the shipped app — any invoke returns this
 *  only until the real implementation lands.
 */
{ kind: "notImplemented"; detail: {
	command: string,
} };

export type AuthAttrView = {
	key: string,
	value: string | null,
	/**  จริงเมื่อ key เข้าข่าย credential (FR-032) — หน้า S2 ใช้ซ่อน/reveal */
	sensitive: boolean,
};

/**  ระดับที่ auth ที่แสดงได้มาจาก — ตัว `source` ของ auth ที่แสดงผล (FR-030) */
export type AuthSourceView = 
/**  auth ของ node ตัวเอง */
{ kind: "own" } | 
/**  สืบทอดจาก folder — พกชื่อ folder ตัวประกาศไว้ให้ label */
{ kind: "folder"; name: string } | 
/**  สืบทอดจาก collection */
{ kind: "collection" } | 
/**  ไม่มี auth ตรงไหนเลย (null/absent ตลอดสาย) */
{ kind: "none" };

/**  effective auth ที่จะแสดง (FR-030) — พร้อมแหล่งที่มาสำหรับป้าย "inherited from" */
export type AuthView = {
	source: AuthSourceView,
	/**  ผ่านมาอย่าง verbatim แม้เป็นชนิดที่ minim ไม่รู้จัก (FR-031) */
	authType: string,
	attributes: AuthAttrView[],
};

/**
 *  body แบบ tagged union ครบทั้งห้า mode (FR-026) — mode ที่ไม่ได้ handle = compile
 *  error ที่ frontend ไม่ใช่พาเนลว่างดำ
 */
export type BodyView = { mode: "raw"; 
/**  จาก `options.raw.language`; ไม่ได้ประกาศเป็น `"text"` (FR-027) */
language: string; text: string } | { mode: "urlencoded"; params: ParamView[] } | { mode: "formdata"; fields: FormFieldView[] } | { mode: "file"; src: string } | { mode: "graphql"; query: string; variables: string };

/**
 *  ภาพรวม collection — payload ของ `open_collection`/`reload_collection` หนึ่งครั้ง
 * 
 *  ส่ง summary ทั้งหมดก่อน ([ADR-005](design.md#key-decisions)) แล้วให้ UI โหลด
 *  detail ของ node ที่เลือกเข้ามาทีละตัวผ่าน `get_node_detail`
 */
export type CollectionOverview = {
	name: string,
	description: string,
	/**  ค่าจาก `info.schema` ตามที่หน้า S4 แสดง */
	schema: string,
	/**
	 *  `info.version` ในรูป display string — object form ประกอบเป็น "major.minor.patch"
	 *  เดิม `identifier` ต่อท้ายเป็น "-<identifier>" (TC-UNIT-048)
	 */
	version: string | null,
	sourcePath: string,
	/**
	 *  ขนาดไฟล์เป็นไบต์ — `u32` เพราะ specta ห้าม bigint ออก wire (JS number
	 *  เก็บได้แม่นสุด 2^53) ใช้เกิน 4 GiB คือเกินจริงสำหรับ collection จริง
	 */
	fileSizeBytes: number,
	requestCount: number,
	folderCount: number,
	variables: VariableView[],
	auth: AuthView | null,
	events: ScriptView[],
	/**
	 *  ต้นไม้ลำดับเอกสาร — ไม่รวม node รากของ collection (S4 ใช้ `collection_overview`
	 *  เองเป็น data source, TC-CMD-019)
	 */
	tree: TreeNode[],
	warnings: LoadWarningView[],
};

export type CookieView = {
	name: string | null,
	value: string | null,
	domain: string,
	path: string,
};

/**  saved response ทั้งตัว (S5) — payload ของ `get_example` */
export type ExampleDetail = {
	name: string,
	status: string | null,
	code: number | null,
	headers: HeaderView[],
	cookies: CookieView[],
	body: string | null,
	/**  `_postman_previewlanguage` — ใช้เลือก syntax highlight */
	previewLanguage: string | null,
};

/**
 *  สรุป example หนึ่งตัวที่ติดไปกับ request — ตัว body มาแยกตอน `get_example`
 *  (ADR-005 / FR-037)
 */
export type ExampleSummary = {
	/**  ตำแหน่งใน array `response` (document order) — key ของ `get_example` */
	index: number,
	name: string,
	status: string | null,
	code: number | null,
};

/**  detail ของ folder node — หน้าจอ S3: script / auth / variable ของ folder เอง */
export type FolderDetail = {
	id: string,
	name: string,
	folderPath: string[],
	description: string,
	auth: AuthView,
	events: ScriptView[],
	variable: VariableView[],
	/**  ลูกตรงๆ กี่ตัว (ตาม arena) */
	childCount: number,
	/**  ลูกหลานที่เป็น request ทั้งหมดกี่ตัว — ตัวเลขบนป้ายของ S3 */
	descendantRequestCount: number,
};

export type FormFieldKind = "text" | "file";

export type FormFieldView = {
	key: string,
	kind: FormFieldKind,
	/**  text field เท่านั้น */
	value: string | null,
	/**  file field เท่านั้น — src แบบ array (ท้ายสุดของ `type: "file"`) join ด้วย ", " */
	src: string | null,
	contentType: string | null,
};

export type HeaderView = {
	key: string,
	value: string,
	disabled: boolean | null,
	description: string,
};

/**  คู่ key/value แบบ display — ใช้กับ `behavior` และ `extra` */
export type KeyValue = {
	key: string,
	value: string,
};

/**
 *  คำเตือนระหว่างโหลด — รูป serializable ที่ข้าม IPC ได้ (FR-009 / design.md §LoadWarning)
 * 
 *  `normalize::LoadWarning` (T-007) มีแค่สอง variant และไม่พกเส้น node; ทุก variant
 *  ที่ design กำหนดมีอยู่ที่นี่ และ mapping จะเติม `node_id` ให้เมื่อรู้
 */
export type LoadWarningView = 
/**  `auth.type` ที่ไม่ใช่ 11 ชนิดที่ schema กำหนด (FR-031 fallback) */
{ kind: "unknownAuthType"; detail: {
	node_id: string | null,
	detail: string,
} } | 
/**  `body.mode` ที่ไม่ใช่ห้า mode ที่รู้จัก */
{ kind: "unknownBodyMode"; detail: {
	node_id: string | null,
	detail: string,
} } | 
/**  raw header block มีบรรทัดที่ไม่มี `:` (ข้ามบรรทัดนั้นไปแล้ว) */
{ kind: "malformedRawHeaderLine"; detail: {
	node_id: string | null,
	detail: string,
} } | 
/**  item ที่ไม่มีทั้ง `item` และ `request` */
{ kind: "itemNeitherGroupNorRequest"; detail: {
	node_id: string | null,
	detail: string,
} } | 
/**  collection variable ประกาศ key ซ้ำ (ตัวแรกชนะ) */
{ kind: "duplicateVariableKey"; detail: {
	node_id: string | null,
	detail: string,
} };

/**
 *  detail ของ node ตัวเดียว — หน้าจอ S2 (request) / S3 (folder)
 * 
 *  internally-tagged ตัวเป็น `kind` เพื่อให้ frontend switch ได้ exhaustive
 *  DTO สำหรับหน้าจอ detail (S4) — ตัวคืนค่าจาก `get_node_detail` ผ่าน wire
 *  (TC-CMD-019): Request เป็น Box เพื่อให้ enum มีขนาดสม่ำเสมอ
 */
export type NodeDetail = {
	kind: "folder",
} & FolderDetail | {
	kind: "request",
} & RequestDetail;

/**
 *  kind ของ node ใน tree — ใช้เป็น serde tag ให้ TS switch ได้หมด (ตัว compile error
 *  ถ้ามี node ชนิดใหม่โผล่)
 */
export type NodeKindView = "folder" | "request";

/**  query / path variable / urlencoded parameter — ถ้วนหน้าใช้ตัวเดียว */
export type ParamView = {
	/**  key ที่หายไปเป็น `""` ไม่ panic */
	key: string,
	value: string | null,
	disabled: boolean | null,
	description: string,
};

/**
 *  preference ของผู้ใช้ที่เก็บใน `store.json` — ต้อง `Deserialize` เพราะเป็น
 *  argument ของ `set_preferences` (T-009)
 */
export type Preferences = {
	theme: Theme,
};

/**
 *  หนึ่งรายการใน recents (design.md §Persistence) — พฤติกรรม MRU/cap เป็นงาน T-010
 * 
 *  `Deserialize` จำเป็นหลัง T-010 เพราะ recents ถูกอ่านกลับจาก store file
 *  (`commands/session.rs`); รูปไฟล์เป็น camelCase เดียวกับ wire shape
 */
export type RecentEntry = {
	path: string,
	name: string,
	/**  unix seconds ของเวลาที่เปิดล่าสุด — `u32` ใช้ได้ถึงปี 2106 (specta ห้าม i64) */
	openedAt: number,
	requestCount: number,
};

/**  detail ของ request leaf — หน้าจอ S2 ครบทุก tab */
export type RequestDetail = {
	id: string,
	name: string,
	folderPath: string[],
	description: string,
	method: string,
	url: UrlView,
	headers: HeaderView[],
	body: BodyView | null,
	auth: AuthView,
	events: ScriptView[],
	behavior: KeyValue[],
	examples: ExampleSummary[],
	variableRefs: VarRef[],
	extra: KeyValue[],
};

export type ScriptView = {
	/**  `"prerequest"` | `"test"` | อะไรก็ตามที่ schema อนุญาต — ผ่านตามเดิม */
	listen: string,
	source: string,
	disabled: boolean | null,
};

/**  Which side of the persistence layer failed — the `"read" | "write"` union of the wire shape. */
export type StoreOperation = "read" | "write";

export type Theme = "system" | "light" | "dark";

/**  node หนึ่งเส้นใน tree (เรียง document order, ซ้อนตาม folder) */
export type TreeNode = {
	id: string,
	name: string,
	kind: NodeKindView,
	/**  เส้น folder ราก → current folder ไม่รวมตัวเอง (FR-015) */
	folderPath: string[],
	/**  requests เท่านั้น; folders เป็น `None` */
	method: string | null,
	/**  requests เท่านั้น; หน้า S2 เอาไปเป็น url pill */
	urlPreview: string | null,
	children: TreeNode[],
	exampleCount: number,
	hasScripts: boolean,
};

/**
 *  url หลัง normalize — `raw` คือ display string ที่ใช้ได้เลย (FR-010) ส่วน
 *  protocol/host/port/path เป็นของแยกให้ UI render ได้ถ้าอยากได้
 */
export type UrlView = {
	raw: string,
	protocol: string | null,
	host: string | null,
	port: string | null,
	path: string | null,
	query: ParamView[],
	pathVariables: ParamView[],
};

/**  ตัวแปรที่ request เอ่ยถึงใน `{{name}}` พร้อมบอกว่ามีนิยามไว้ใน collection หรือไม่ */
export type VarRef = {
	name: string,
	defined: boolean,
};

/**  ตัวแปรระดับ collection (และ folder/node) — `type` เป็นชื่อฟิลด์ wire จริง */
export type VariableView = {
	key: string,
	value: string | null,
	type: string | null,
	disabled: boolean | null,
	description: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

